services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DOCKER_CONTAINER=true
      - DB_DIALECT=mysql
      - DB_HOST=mysql
      - DB_NAME=mern_assessment
      - DB_USERNAME=root
      - DB_PASSWORD=mYR00t_paSS
      - DB_PORT=3306
      - SECRET=mysecretkey
      - REDIS_HOST=redis  # Instead of localhost or 127.0.0.1
      - REDIS_PORT=6379   # Default Redis port
    depends_on:
      - mysql
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=mYR00t_paSS
      - MYSQL_DATABASE=mern_assessment
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
